/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VirusFrame.UnclosableWindow;

import com.formdev.flatlaf.FlatDarkLaf;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author mantu
 */
public class Messaggio extends javax.swing.JFrame {

    /**
     * Creates new form Messaggio
     */
    
    char c;
    Evento evento;
    
    
    public Messaggio(Evento evento) {
        initComponents();
        
        try {
            // Leggi Lingua
            FileReader lingua= new FileReader("src/TXTfiles/lingua.txt");
            c=(char)lingua.read();
            lingua.close();
            cambioLingua();
        } catch (IOException ex) {
            // errore
        }
        
        this.evento=evento;
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon.png")));
    }
    
    private void cambioLingua(){
        
        if(c=='0'){
            this.setTitle("Informazioni messaggio");
            lableTitolo.setText("Titolo:");
            labelMessaggio.setText("Messaggio:");
            bntSalva.setText("Salva");
        }
        else if(c=='1'){
            this.setTitle("Message information");
            lableTitolo.setText("Title:");
            labelMessaggio.setText("Message:");
            bntSalva.setText("Save");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lableTitolo = new javax.swing.JLabel();
        labelTitolo = new javax.swing.JTextField();
        labelMessaggio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaMessaggio = new javax.swing.JTextArea();
        bntSalva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(19, 19, 19));
        jPanel1.setToolTipText("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Freccia.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        lableTitolo.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lableTitolo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lableTitolo.setText("Titolo:");

        labelMessaggio.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        labelMessaggio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMessaggio.setText("Messaggio:");

        textAreaMessaggio.setColumns(20);
        textAreaMessaggio.setLineWrap(true);
        textAreaMessaggio.setRows(5);
        textAreaMessaggio.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textAreaMessaggio);

        bntSalva.setText("Salva");
        bntSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lableTitolo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelTitolo))
                    .addComponent(jLabel3)
                    .addComponent(labelMessaggio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bntSalva)
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(labelMessaggio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntSalva)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
        evento.setRadio(-1);
        SelezionaEvento frame= new SelezionaEvento(evento);
        frame.show();
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void bntSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvaActionPerformed
        // TODO add your handling code here:
        
        String titolo=labelTitolo.getText();
        String mess=textAreaMessaggio.getText();
        
        if(titolo.isEmpty()){
            if(c=='0'){
                JOptionPane.showMessageDialog(null, "Inserisci un titolo", "Errore",JOptionPane.WARNING_MESSAGE);
            }
            else if(c=='1'){
                JOptionPane.showMessageDialog(null, "Enter a title", "Error",JOptionPane.WARNING_MESSAGE);
            }
            
            return;
        }
        
        if(mess.isEmpty()){
            if(c=='0'){
                JOptionPane.showMessageDialog(null, "Inserisci un messaggio", "Errore",JOptionPane.WARNING_MESSAGE);
            }
            else if(c=='1'){
                JOptionPane.showMessageDialog(null, "Enter a message", "Error",JOptionPane.WARNING_MESSAGE);
            }
            
            return;
        }
        
        evento.setTitolo(titolo);
        evento.setContenuto(mess);
        
        UnclosableWindow frame= new UnclosableWindow();
        frame.show();
        frame.aggiornaModel();
        frame.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_bntSalvaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Messaggio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Messaggio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Messaggio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Messaggio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatDarkLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Messaggio(new Evento(0,0,"","")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSalva;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMessaggio;
    private javax.swing.JTextField labelTitolo;
    private javax.swing.JLabel lableTitolo;
    private javax.swing.JTextArea textAreaMessaggio;
    // End of variables declaration//GEN-END:variables
}
