/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VirusFrame.UnclosableWindow;
import VirusFrame.UnclosableWindow.*;

import com.formdev.flatlaf.FlatDarkLaf;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.DefaultListModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mantu
 */

public class SelezionaEvento extends javax.swing.JFrame {

    /**
     * Creates new form SelezionaEvento
     */
    
    Evento evento;
    
    DefaultListModel modelMesaggi= new DefaultListModel<>();
    DefaultListModel modelEventi= new DefaultListModel<>();
    
    // Array
    ArrayList<String> messaggi= new ArrayList<>();
    ArrayList<String> eventi= new ArrayList<>();
    
    char c;
    
    public SelezionaEvento(Evento evento) {
        initComponents();
        setLocationRelativeTo(null);
        // Icon
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon.png")));
        
        rbtnMessaggio.setSelected(true);
        
        try {
            // Leggi Lingua
            FileReader lingua= new FileReader("src/TXTfiles/lingua.txt");
            c=(char)lingua.read();
            lingua.close();
            cambioLingua();
        } catch (IOException ex) {
            // errore
        }
        
        rbtnMessaggio.setSelected(true);
        listaAzioni.setModel(modelMesaggi);
        
        this.evento=evento;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scelta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbtnEvento = new javax.swing.JRadioButton();
        rbtnMessaggio = new javax.swing.JRadioButton();
        labelSelezionaAzione = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAzioni = new javax.swing.JList<>();
        labelScegliAzione = new javax.swing.JLabel();
        btnAvanti = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(19, 19, 19));

        scelta.add(rbtnEvento);
        rbtnEvento.setText("Evento");
        rbtnEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEventoActionPerformed(evt);
            }
        });

        scelta.add(rbtnMessaggio);
        rbtnMessaggio.setSelected(true);
        rbtnMessaggio.setText("Messaggio          ");
        rbtnMessaggio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMessaggioActionPerformed(evt);
            }
        });

        labelSelezionaAzione.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        labelSelezionaAzione.setForeground(new java.awt.Color(255, 255, 255));
        labelSelezionaAzione.setText("Seleziona azione:");

        listaAzioni.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Errore", "Avviso", "Informazione" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaAzioni);

        labelScegliAzione.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        labelScegliAzione.setForeground(new java.awt.Color(255, 255, 255));
        labelScegliAzione.setText("Scegli azione:");

        btnAvanti.setText("Avanti");
        btnAvanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvantiActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Freccia.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAvanti)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnMessaggio)
                                    .addComponent(rbtnEvento)
                                    .addComponent(labelSelezionaAzione))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelScegliAzione)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSelezionaAzione, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelScegliAzione, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtnMessaggio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnEvento))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAvanti)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambioLingua(){
        
        messaggi.clear();
        eventi.clear();
        
        if(c=='0'){
            labelSelezionaAzione.setText("Seleziona azione:");
            rbtnMessaggio.setText("Messaggio");
            rbtnEvento.setText("Evento");
            labelScegliAzione.setText("Scegli azione:");
            btnAvanti.setText("Avanti");
            
            //Array
            messaggi.add("Errore");
            messaggi.add("Avviso");
            messaggi.add("Informazione");
            
            updateModel(messaggi,modelMesaggi);
            
            eventi.add("Spegni pc");
            eventi.add("Riavvia pc");
            eventi.add("Disconetti utente");
            eventi.add("Blocca pc");
            
            updateModel(eventi,modelEventi);
            
            // Titolo
            this.setTitle("Aggiungi azione");
        }
        else if(c=='1'){
            labelSelezionaAzione.setText("Select action:");
            rbtnMessaggio.setText("Message");
            rbtnEvento.setText("Event");
            labelScegliAzione.setText("Choose action:");
            btnAvanti.setText("Next");
            
            //Array
            messaggi.add("Error");
            messaggi.add("Attention");
            messaggi.add("Information");
            
            updateModel(messaggi,modelMesaggi);
            
            eventi.add("Turn off the pc");
            eventi.add("Restart pc");
            eventi.add("User logout");
            eventi.add("Lock pc");
            
            updateModel(eventi,modelEventi);
            
            // Titolo
            this.setTitle("Add action");
        }
    }
    
    private void updateModel(ArrayList v,DefaultListModel model){
        model.addAll(v);
    }
    
    private void getEvent(){
        int index=listaAzioni.getSelectedIndex();
        int radio;
        
        if(index==-1){
            
            if(c=='0'){
                JOptionPane.showMessageDialog(null, "Seleziona prima un elemento della lista", "Errore",JOptionPane.WARNING_MESSAGE);
                return;
            }
            else if(c=='1'){
                JOptionPane.showMessageDialog(null, "Select an item from the list first", "Error",JOptionPane.WARNING_MESSAGE);
                return;
            }
            return;
        }
        

        if(rbtnMessaggio.isSelected()){
            radio=0;
            evento.setRadio(radio);
            evento.setAzione(index);
        }
        else if(rbtnEvento.isSelected()){
            radio=1;
            evento.setRadio(radio);
            evento.setAzione(index);
        }
    }
    
    private void rbtnMessaggioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMessaggioActionPerformed
        // TODO add your handling code here:
        listaAzioni.clearSelection();
        listaAzioni.setModel(modelMesaggi);
    }//GEN-LAST:event_rbtnMessaggioActionPerformed

    private void btnAvantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvantiActionPerformed
        // TODO add your handling code here:
        getEvent();
        
        if(rbtnMessaggio.isSelected()){
            Messaggio frame =new Messaggio(evento);
            frame.show();
            frame.setLocationRelativeTo(null);
            evento.setRadio(0);
            evento.setAzione(listaAzioni.getSelectedIndex());
            this.dispose();
        }
        else if(rbtnEvento.isSelected()){
            UnclosableWindow frame=new UnclosableWindow();
            frame.show();
            frame.setLocationRelativeTo(null);
            evento.setRadio(1);
            evento.setAzione(listaAzioni.getSelectedIndex());
            frame.aggiornaModel();
            this.dispose();
        }
    }//GEN-LAST:event_btnAvantiActionPerformed

    private void rbtnEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEventoActionPerformed
        // TODO add your handling code here:
        listaAzioni.clearSelection();
        listaAzioni.setModel(modelEventi);
    }//GEN-LAST:event_rbtnEventoActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        UnclosableWindow frame =new UnclosableWindow();
        frame.show();
        frame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelezionaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelezionaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelezionaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelezionaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatDarkLaf.setup();
        /* Create and display the form */
           java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new SelezionaEvento(new Evento(0,0,"","")).setVisible(true); // // mettere nelle parentei i parametri noti
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanti;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelScegliAzione;
    private javax.swing.JLabel labelSelezionaAzione;
    private javax.swing.JList<String> listaAzioni;
    private javax.swing.JRadioButton rbtnEvento;
    private javax.swing.JRadioButton rbtnMessaggio;
    private javax.swing.ButtonGroup scelta;
    // End of variables declaration//GEN-END:variables
}
